version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        NODE_VERSION: lts/*
    container_name: PeluqueriaDB
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    command: sleep infinity
    
volumes:
  mssql_data:
