version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        NODE_VERSION: lts/*
    container_name: PeluqueriaDB
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DB_SERVER=serverpeluqueria.database.windows.net
      - DB_USER=admindb
      - DB_PASSWORD=SQLServer2023!
      - DB_NAME=PeluqueriaDB
      - DB_PORT=1433
    command: sleep infinity
    
volumes:
  mssql_data:
