version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server_express
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SQLServer2023!"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./db/init.sql:/init.sql
    command: >
      /bin/bash -c "
        /opt/mssql/bin/sqlservr & 
        sleep 30 && 
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'SQLServer2023!' -i /init.sql
      "

  backend:
    build: ./backend
    container_name: backend_peluqueria
    env_file: ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend_peluqueria
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  mssql_data:
