version: '3.9'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile.sqlserver
    container_name: sql_server_express
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SQLServer2023!"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./db/init.sql:/var/opt/mssql/init.sql
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr & 
      sleep 60 && 
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'SQLServer2023!' -i /var/opt/mssql/init.sql
      "

  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    deploy:
     resources:
       limits:
         memory: 4g

volumes:
  mssql_data: