version: '3.9'

services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DB_SERVER=serverpeluqueria.database.windows.net
      - DB_USER=admindb
      - DB_PASSWORD=SQLServer2023!
      - DB_NAME=PeluqueriaDB
      - DB_PORT=1433
    deploy:
      resources:
        limits:
          memory: 4g

volumes:
  mssql_data:
