version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    
    user: vscode 
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../..:/workspaces:cached
    
    environment:
      - PYTHONUNBUFFERED=1
      - WORKSPACE_PERMISSIONS=755  
    ports:
      - "${BACKEND_PORT}:8080"
    entrypoint: /usr/local/share/docker-init.sh
    command: >
      sh -c "chown -R vscode:vscode /workspaces &&
             chmod -R 755 /workspaces &&
             sleep infinity"
    

    working_dir: /workspaces/PeluqueriaDB